#!/bin/sh

rm Robbery_Accident_Fire_Database2/Fire/6.jpg
rm Robbery_Accident_Fire_Database2/Fire/119.jpg
rm Robbery_Accident_Fire_Database2/Fire/123.jpg
rm Robbery_Accident_Fire_Database2/Fire/125.jpg
rm Robbery_Accident_Fire_Database2/Fire/127.jpg
rm Robbery_Accident_Fire_Database2/Fire/162.jpg
rm Robbery_Accident_Fire_Database2/Fire/192.jpg
rm Robbery_Accident_Fire_Database2/Fire/193.jpg
rm Robbery_Accident_Fire_Database2/Fire/243.jpg
rm Robbery_Accident_Fire_Database2/Fire/249.jpg
rm Robbery_Accident_Fire_Database2/Fire/269.jpg
rm Robbery_Accident_Fire_Database2/Fire/275.jpg
rm Robbery_Accident_Fire_Database2/Fire/284.jpg
rm Robbery_Accident_Fire_Database2/Fire/316.jpg
rm Robbery_Accident_Fire_Database2/Fire/317.jpg
rm Robbery_Accident_Fire_Database2/Fire/414.jpg
rm Robbery_Accident_Fire_Database2/Fire/500.jpg
rm Robbery_Accident_Fire_Database2/Fire/502.jpg
rm Robbery_Accident_Fire_Database2/Fire/513.jpg
rm Robbery_Accident_Fire_Database2/Fire/525.jpg
rm Robbery_Accident_Fire_Database2/Fire/526.jpg
rm Robbery_Accident_Fire_Database2/Fire/531.jpg
rm Robbery_Accident_Fire_Database2/Fire/539.jpg
rm Robbery_Accident_Fire_Database2/Fire/546.jpg
rm Robbery_Accident_Fire_Database2/Fire/547.jpg
rm Robbery_Accident_Fire_Database2/Fire/562.jpg
rm Robbery_Accident_Fire_Database2/Fire/566.jpg
rm Robbery_Accident_Fire_Database2/Fire/574.jpg
rm Robbery_Accident_Fire_Database2/Fire/575.jpg
rm Robbery_Accident_Fire_Database2/Fire/597.jpg
rm Robbery_Accident_Fire_Database2/Fire/602.jpg
rm Robbery_Accident_Fire_Database2/Fire/607.jpg
rm Robbery_Accident_Fire_Database2/Fire/608.jpg
rm Robbery_Accident_Fire_Database2/Fire/646.jpg
rm Robbery_Accident_Fire_Database2/Fire/651.jpg
rm Robbery_Accident_Fire_Database2/Fire/657.jpg
rm Robbery_Accident_Fire_Database2/Fire/670.jpg
rm Robbery_Accident_Fire_Database2/Fire/671.jpg
rm Robbery_Accident_Fire_Database2/Fire/682.jpg
rm Robbery_Accident_Fire_Database2/Fire/683.jpg
rm Robbery_Accident_Fire_Database2/Fire/686.jpg
rm Robbery_Accident_Fire_Database2/Fire/688.jpg
rm Robbery_Accident_Fire_Database2/Fire/696.jpg
rm Robbery_Accident_Fire_Database2/Fire/706.jpg
rm Robbery_Accident_Fire_Database2/Fire/707.jpg
rm Robbery_Accident_Fire_Database2/Fire/733.jpg
rm Robbery_Accident_Fire_Database2/Fire/740.jpg
rm Robbery_Accident_Fire_Database2/Fire/764.jpg
rm Robbery_Accident_Fire_Database2/Fire/765.jpg
rm Robbery_Accident_Fire_Database2/Fire/777.jpg
rm Robbery_Accident_Fire_Database2/Fire/790.jpg
rm Robbery_Accident_Fire_Database2/Fire/802.jpg
rm Robbery_Accident_Fire_Database2/Fire/808.jpg
rm Robbery_Accident_Fire_Database2/Fire/828.jpg
rm Robbery_Accident_Fire_Database2/Fire/853.jpg
rm Robbery_Accident_Fire_Database2/Fire/885.jpg
rm Robbery_Accident_Fire_Database2/Fire/923.jpg
rm Robbery_Accident_Fire_Database2/Fire/942.jpg
rm Robbery_Accident_Fire_Database2/Fire/945.jpg
rm Robbery_Accident_Fire_Database2/Fire/946.jpg
rm Robbery_Accident_Fire_Database2/Fire/954.jpg
rm Robbery_Accident_Fire_Database2/Fire/978.jpg
rm Robbery_Accident_Fire_Database2/Fire/980.jpg
rm Robbery_Accident_Fire_Database2/Fire/994.jpg
rm Robbery_Accident_Fire_Database2/Fire/1007.jpg
rm Robbery_Accident_Fire_Database2/Fire/1011.jpg
rm Robbery_Accident_Fire_Database2/Fire/1017.jpg
rm Robbery_Accident_Fire_Database2/Fire/1043.jpg
rm Robbery_Accident_Fire_Database2/Fire/1048.jpg
rm Robbery_Accident_Fire_Database2/Fire/1094.jpg
rm Robbery_Accident_Fire_Database2/Fire/1097.jpg
rm Robbery_Accident_Fire_Database2/Fire/1117.jpg
rm Robbery_Accident_Fire_Database2/Fire/1124.jpg
rm Robbery_Accident_Fire_Database2/Fire/1140.jpg
rm Robbery_Accident_Fire_Database2/Fire/1184.jpg
rm Robbery_Accident_Fire_Database2/Fire/1214.jpg
rm Robbery_Accident_Fire_Database2/Fire/1218.jpg
rm Robbery_Accident_Fire_Database2/Fire/1227.jpg
rm Robbery_Accident_Fire_Database2/Fire/1256.jpg
rm Robbery_Accident_Fire_Database2/Fire/1257.jpg
rm Robbery_Accident_Fire_Database2/Fire/1264.jpg
rm Robbery_Accident_Fire_Database2/Fire/1324.jpg
rm Robbery_Accident_Fire_Database2/Fire/1332.jpg
rm Robbery_Accident_Fire_Database2/Fire/1338.jpg
rm Robbery_Accident_Fire_Database2/Fire/1344.jpg
rm Robbery_Accident_Fire_Database2/Fire/1350.jpg
rm Robbery_Accident_Fire_Database2/Fire/1363.jpg
rm Robbery_Accident_Fire_Database2/Fire/1375.jpg
rm Robbery_Accident_Fire_Database2/Fire/1378.jpg
rm Robbery_Accident_Fire_Database2/Fire/1402.jpg